### PR TITLE
feat(issues): Include Github issue template

### PR DESCRIPTION
**Pull request by placer14**

### CODE REVIEW

**Comment by placer14** [comment]
This may need to be scoped to specific orgs that @stongo can actually administer (and redirect to other DRIs for the orgs which cannot be handled. 

@stongo can you answer:
- Which orgs can we handle?
- Which orgs SHOULD we handle (so that we can have NetOps added as admin)?
- Who else should be DRI for these requests. Ideally we'd have two (bus-factor).

**Comment by placer14** [comment]
libp2p GH management is handled in another repo:
> For this, you can open a PR in which you add Karol to the team here: https://github.com/libp2p/github-mgmt/blob/master/github/libp2p.yml#L3248
> Remember to add him to the org as well: https://github.com/libp2p/github-mgmt/blob/master/github/libp2p.yml#L16

(source: @galargh in FIL Slack)

We should also create a separate item specific for libp2p GH requests. And probably need to split this into multiple org-specific templates in their appropriate repos.

**Comment by galargh** [comment]
BTW, we have GitHub Management repos in the following orgs
- https://github.com/ipfs/github-mgmt
- https://github.com/ipfs-shipyard/github-mgmt
- https://github.com/filecoin-shipyard/github-mgmt
- https://github.com/libp2p/github-mgmt
- https://github.com/ipld/github-mgmt
- https://github.com/multiformats/github-mgmt
- https://github.com/testground/github-mgmt
- https://github.com/pl-strflt/github-mgmt (this one is currently used only by the IPDX team)

**Comment by stongo** [comment]
to become a DRI, I would need access to repos listed in the on-boarding templates, which I currently do not have. 
otherwise I'll just be an intermediary request chaser.

**Comment by placer14** [comment]
This is going to be handled outside of NetOps. Closing.

**Pull request closed without merging**
